add score
KasiaFernandes/Quiz pull request #5
Opened 2017-12-07 18:19 UTC by KasiaFernandes

Hello! :) Ok, TROCHĘ działa. Dodałam score (w komponencie Title) i po klikaniu na odpowiedzi odpowiednio zmienia się liczba punktów. ALE teraz widzę, że funkcja getRandomQuestion nie powinna być przypisana do jakiegoś guzika tylko być uruchamiana wtedy kiedy onAnswer. Czy powinnam ją jakoś włączyć do onAnswer? Bo nie mogę chyba mieć kilku onClick'ów na odpowiedziach, prawda? (to chyba idiotyczne pytanie, nawet nie wiem jak to miałoby wyglądać). Dziękuję! :)

2017-12-08 08:10 UTC, apieceofbart requested changes

2017-12-08 08:10 UTC, apieceofbart commented on client/Game.js
> +    onAnswer(answer) {
Mysle sobie ze to powinno wygladac tak:
1. gracz klika na odpowiedz (co wywoluje funkcje onAnswer)
2. dodajemy punkt (albo nie)
3. losujemy nastepne pytanie

Do losowania pytania mamy juz cala funkcje `getRandomQuestion` wiec mozemy jej jakos uzyc w `onAnswer`.
Usunmy linijki z `onAnswer` ktore sa kopiami z `getRandomQuestion` 38, 39 i 40.

2017-12-08 08:10 UTC, apieceofbart commented on client/Game.js
> +        if (answer.correct == true) {
zrobmy sobie tutaj dodatkowa zmienna np. `pointsToAdd` . Niech ona bedzie rowna `answer.correct`
Wyglada to troche bez sensu bo `answer.correct` to jest boolean czyli true albo false ale dla javascriptu to prawie to samo co 1 i 0. 
Wiec mozemy troche oszukac i dodac do naszego wyniku `true` albo `false` co bedzie oznaczac ze dodamy 1 albo 0.

2017-12-08 08:10 UTC, apieceofbart commented on client/Game.js
> +            this.setState({
Jak juz bedziemy miec ta zmienna to nie bedzie nam potrzebny ten `if` po prostu zrobmy:
```
this.setState({ 
  score: score + pointsToAdd
})
```
W ten sposob zalatwimy oba przypadki za jednym razem (czasami bedzie dodawac zero - wiec to pozornie bez sensu ale kod wyglada prosciej - poza tym byc moze kiedys bedziemy chcieli dawac ujemne punkty za zle odpowiedzi etc.)

Na samym koncu musimy jeszcze wylosowac nowe pytanie czyli poprostu
`this.getRandomQuestion();`

Tutaj musze zrobic dygresje ze poniewaz funckcja `setState` jest asynchroniczna to nie ma gwarancji ze nie bedzie tak ze np. najpier wykona sie `this.getRandomQuestion()` a dopiero pozniej komponent zmieni stan i doda punkty. W tym przypadku to i tak sie wykona tak szybko ze tego nie zauwazymy. No ale zeby sobie radzic w takich przypadkach to sposob jest taki ze to `setState` jako drugi parametr mozna podac callback - funkcja ktora ma sie wykonac jak juz `state` zostaniemy zupdatowany. Wtedy mamy pewnosc ze kolejnosc bedzie zachowana.
Wygladalo by to tak:
```
        this.setState({
            score: score + pointsToAdd
        }, () => {
            this.getRandomQuestion();
        });
```

2017-12-08 08:10 UTC, apieceofbart commented on client/Game.js
>                          <button onClick={this.getRandomQuestion}>GET QUESTION!</button>
Czy w takim razie ten guzik jest nam w ogole jeszcze potrzebny? (skoro bedziemy losowac pytanie po kazdej odpowiedzi?)

2017-12-09 10:09 UTC, KasiaFernandes commented on client/Game.js
> +    onAnswer(answer) {
Dokładnie tak to powinno wyglądać :)

2017-12-09 10:10 UTC, KasiaFernandes commented on client/Game.js
> +        if (answer.correct == true) {
Sprytne! Done!

2017-12-09 10:10 UTC, KasiaFernandes commented on client/Game.js
>                          <button onClick={this.getRandomQuestion}>GET QUESTION!</button>
guzik nie jest potrzebny, wywaliłam go

2017-12-09 12:44 UTC, apieceofbart approved these changes
o to chodzilo! (z imieniem)

2017-12-09 13:26 UTC, KasiaFernandes commented
Kurczę, już nic nie rozumiem :( Teraz generalnie też jest ok, ale niektóre pytania powtarzają się dwa-trzy razy  (np. udało mi się uzyskać score 11 i 12)

2017-12-09 14:20 UTC, apieceofbart commented
hmm no to moja wina - znowu tego nie przemyslalem (The biggest sloppiness award goes too..)
Chodzi oto ze jak wywolujemy `removeQuestion` a pozniej `getRandomQuestion` to obie korzystaja z `setState` ktory nie jest synchroniczny - nie mamy gwarancji ze najpierw sie usunie a pozniej wylosuje juz z nowej puli. No i stad te problemy - `this.state` nie zawsze oznacza aktualnego stanu (tzn. takiego jak bysmy chcieli). 

Jak temu zaradzic? Wystarczy lekko zmodyfikowac `this.setState`. Normalnie to jest funkcja ktora przyjmuje nowy obiekt stanu, np.
```
const selectedQIndex = Math.floor(Math.random() * this.state.questionsData.length);
const selectedQuestion = this.state.questionsData[selectedQIndex];

this.setState({
  selectedQuestion: selectedQuestion
})
```

Alternatywnie mozemy do `setState` przekazac funkcje ktorej parametrem bedzie aktualna wartosc stanu - tutaj mamy gwarancje ze ten stan jest na pewno aktualny.

Czyli zamiast
```
this.setState({
  jakasZmienna: nowaWartosc
})
```
mozem zrobic
```
this.setState(state => {
  return {
    jakasZmienna: nowaWartosc
  }
})
```
W tym konkretnym przypadku `selectedQuestion` to by wygladalo tak:

```
        this.setState(state => {
            const selectedQIndex = Math.floor(Math.random() * state.questionsData.length);
            const selectedQuestion = state.questionsData[selectedQIndex];

            return {
                selectedQuestion: selectedQuestion]
            }
        })
```
Czyli wrzucamy operacje na `state` do srodka `setState` (i zamiast `this.state` uzywamy `state` - tak sie nazywa nasz parametr).

Sprobuj podobnie przerobic `removeQuestion` - wtedy calosc zadziala.

2017-12-09 14:51 UTC, KasiaFernandes commented
Działa! :D Ostatecznie mój wkład w tę mini-aplikację był raczej niewielki ale było to najlepsze ćwiczenie w całym tym kursie. (Sloppiness aside ;)) bardzo, bardzo Ci dziękuję! (w moim mniemaniu) naprawdę dużo się nauczyłam :) Zajmę się teraz stylami, ale zastanawiam się jeszcze czy udałoby się wprowadzić kategorie pytań. Np. po wprowadzeniu imienia użytkownik widziałby listę kategorii do wyboru i dopiero po wyborze kategorii przechodziłby do pytań.

2017-12-09 15:07 UTC, apieceofbart commented
No ja myślałem że dopiero zaczynamy! Kategorie pytań to fajny pomysł, możemy pomyśleć też o zapisywaniu najlepszych wyników, jakiejś konfiguracji (np. Ile pytań ma być w quizie) itd.

2017-12-09 15:25 UTC, KasiaFernandes commented
Haha, super! :D No, ale zobaczymy ile uda się zrobić. 
Aaa, ten "this" wyrzucamy, bo już jest w "this.setState"?

2017-12-09 15:32 UTC, apieceofbart commented
Wyrzucamy bo jak używamy funkcji w setState to jej parametr `state` jest właśnie tym samym co `this.state`

2017-12-10 15:47 UTC, KasiaFernandes commented
Cześć Bartku, pomyślałam, że na koniec dodam też button uruchamiający grę ponownie. Myślałam, że wystarczy wyrenderować inny komponent w onClick, ale to też jest bardziej skomplikowane niż mi się wydawało, bo nie zadziałało. Możemy o tym i o tej stronie z kategoriami pytań pogadać na callu? (Kiedy go mamy?) Może zmerguję już tego brancha? :)

2017-12-10 15:57 UTC, apieceofbart commented
Merguj! Poniedziałek 20?

10.12.2017 4:47 PM "KasiaFernandes" <notifications@github.com> napisał(a):

> Cześć Bartku, pomyślałam, że na koniec dodam też button uruchamiający grę
> ponownie. Myślałam, że wystarczy wyrenderować inny komponent w onClick, ale
> to też jest bardziej skomplikowane niż mi się wydawało, bo nie zadziałało.
> Możemy o tym i o tej stronie z kategoriami pytań pogadać na callu? (Kiedy
> go mamy?) Może zmerguję już tego brancha? :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/KasiaFernandes/Quiz/pull/5#issuecomment-350557280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADnaGFOXgAZhSlsCwhsqKJiCjuinC-V2ks5s-_0AgaJpZM4Q5-nS>
> .
>

2017-12-10 16:05 UTC, KasiaFernandes commented
Jutro o 20:00 mi pasuje :) 
Merguję!

2017-12-10 16:05 UTC, merged